#!/usr/bin/env bash

if [ -z "$SAGE_LOCAL" ]; then
    echo "SAGE_LOCAL undefined ... exiting"
	echo "Maybe run 'sage -sh'?"
	exit 1
fi

sage -t src/surface_dynamics/ --force_lib --long

if [ $? -ne 0 ]
then
	echo "Error: trouble in the surface dynamics library"
	exit 1
fi

echo "All test pass for the surface dynamics library"
