#!/usr/bin/env bash

if [ -z "$SAGE_LOCAL" ]; then
    echo >&2 "SAGE_LOCAL undefined ... exiting"
    echo >&2 "Maybe run 'sage --sh'?"
    exit 1
fi

# Remove old version
rm -fr "$SAGE_LOCAL"/lib/python/site-packages/surface_dynamics*

# Install the python library
cd src
echo "Building surface_dynamics spkg..."
python setup.py install

if [ $? -ne 0 ]; then
    echo >&2 "Error building flatsurf"
    exit 1
fi


# Install databases
if [ -d "$SAGE_SHARE"/flat_surfaces ]
then
    rm -rf "$SAGE_SHARE"/flat_surfaces
fi

mkdir -p "$SAGE_SHARE"/flat_surfaces
tar xf flat_surfaces_data.tar.gz -C "$SAGE_SHARE"/flat_surfaces


# documentation?
#rm -fr "$SAGE_ROOT"/src/sage/doc/en/surface_dynamics
#cp -r doc/en/slabbe "$SAGE_ROOT"/src/doc/en

exit 0
