name: Developer Tasks
on:
  push: { branches: [ "master" ] }
  pull_request: { branches: [ "master" ] }

concurrency:
  group: dev-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.on }}
    strategy:
      matrix:
        on: ["ubuntu-24.04"]
    steps:
    - uses: actions/checkout@v4
      with: { submodules: recursive }
    - uses: prefix-dev/setup-pixi@v0.8.5
      with: { pixi-version: v0.42.1 }
    - run: pixi run sage -c 'import surface_dynamics'
    - run: pixi run -e dev test-doctest
    - run: pixi run -e dev test-doctest-long
    - run: pixi run -e dev test-pytest
    - run: pixi run test
    - run: |
        pixi run doc &

        doc=$!

        while true; do
          if ! kill -0 $doc; then
            exit 1
          fi

          if curl http://localhost:8880/; then
            exit 0
          fi

          sleep 1
        done
